#This action test builds EMHASS standalone Docker images, in each architecture.
name: "Test Docker Standalone"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [
          {buildx: linux/amd64, target_arch: amd64, os_version: debian},
          {buildx: linux/arm/v7, target_arch: armv7, os_version: debian},
          {buildx: linux/arm/v7, target_arch: armhf, os_version: raspbian},
          {buildx: linux/arm64,  target_arch: aarch64, os_version: debian}
        ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform.buildx }}
          build-args: |
            TARGETARCH=${{ matrix.platform.target_arch }}
            os_version=${{ matrix.platform.os_version }}
          tags: emhass
          load: true
      - name: Test # Run docker for 2min, if the output contains waitress   INFO  "Serving on" http://0.0.0.0:5000 assume it worked
        run: timeout 2 docker run --rm -it emhass | grep -q "Serving on"  && echo 0 || echo 1
